In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt  
import seaborn as sns

In [2]:
df= pd.read_csv('../diabetes_dataset/diabetes.csv')

In [5]:
df.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
757,0,123,72,0,0,36.3,0.258,52,1
132,3,170,64,37,225,34.5,0.356,30,1
218,5,85,74,22,0,29.0,1.224,32,1
598,1,173,74,0,0,36.8,0.088,38,1
537,0,57,60,0,0,21.7,0.735,67,0

In [10]:
df=df.iloc[:,2:]

In [11]:
df.sample(5)

     DiabetesPedigreeFunction  Age  Outcome
497                     0.547   25        0
636                     0.153   48        0
641                     0.303   24        0
552                     0.247   66        0
685                     0.591   25        0

Train test split

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('Outcome', axis=1),
                                                            df['Outcome'],
                                                               test_size=0.3,
                                                               random_state=0)

In [15]:
x_train.shape, x_test.shape

((537, 2), (231, 2))

Standard Scaler

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

#fit the scalar to the train set, it will learn the parameters
scaler.fit(x_train)

#transform train and test sets  
x_train_scaled= scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [18]:
scaler.mean_

array([ 0.4713203 , 33.67039106])

In [19]:
x_train

     DiabetesPedigreeFunction  Age
580                     0.371   21
418                     0.624   27
764                     0.340   27
363                     0.520   67
757                     0.258   52
..                        ...  ...
763                     0.171   63
192                     0.383   36
629                     0.148   21
559                     0.300   35
684                     0.640   69

[537 rows x 2 columns]

In [21]:
x_train_scaled

array([[-0.3002719 , -1.05654479],
       [ 0.45699051, -0.55622332],
       [-0.39305899, -0.55622332],
       ...,
       [-0.96774035, -1.05654479],
       [-0.51278428,  0.11087198],
       [ 0.50488062,  2.94602702]], shape=(537, 2))

In [22]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns=x_test.columns)

In [23]:
x_train_scaled

     DiabetesPedigreeFunction       Age
0                   -0.300272 -1.056545
1                    0.456991 -0.556223
2                   -0.393059 -0.556223
3                    0.145705  2.779253
4                   -0.638496  1.528450
..                        ...       ...
532                 -0.898898  2.445706
533                 -0.264354  0.194259
534                 -0.967740 -1.056545
535                 -0.512784  0.110872
536                  0.504881  2.946027

[537 rows x 2 columns]

In [24]:
np.round(x_train.describe(),1)

       DiabetesPedigreeFunction    Age
count                     537.0  537.0
mean                        0.5   33.7
std                         0.3   12.0
min                         0.1   21.0
25%                         0.2   24.0
50%                         0.4   29.0
75%                         0.6   41.0
max                         2.4   81.0

In [25]:
np.round(x_train_scaled.describe(),1)

       DiabetesPedigreeFunction    Age
count                     537.0  537.0
mean                       -0.0    0.0
std                         1.0    1.0
min                        -1.2   -1.1
25%                        -0.7   -0.8
50%                        -0.3   -0.4
75%                         0.4    0.6
max                         5.8    3.9

Effect of Scaling